DROP TABLE IF EXISTS MUSICA;
DROP TABLE IF EXISTS ARTISTA;
DROP TABLE IF EXISTS ESTILO;


CREATE TABLE ARTISTA(
    ID integer AUTO_INCREMENT not null,
    NOME varchar(255),
    primary key(ID)
);

CREATE TABLE ESTILO(
    ID integer AUTO_INCREMENT not null,
    DESCRICAO VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE MUSICA(
    ID integer AUTO_INCREMENT not null,
    NOME VARCHAR(255),
    ESTILO_ID INTEGER NOT NULL,
    ARTISTA_ID INTEGER NOT NULL,
    PRIMARY KEY(ID)
);


INSERT INTO ARTISTA(ID, NOME) VALUES(1, 'Artista 1');
INSERT INTO ARTISTA(ID, NOME) VALUES(2, 'Artista 2');

INSERT INTO ESTILO(ID, DESCRICAO) VALUES(1, 'Estilo 1');
INSERT INTO ESTILO(ID, DESCRICAO) VALUES(2, 'Estilo 2');

INSERT INTO MUSICA(ID, NOME, ESTILO_ID, ARTISTA_ID) VALUES(1, 'Musica 1', 1, 1);
INSERT INTO MUSICA(ID, NOME, ESTILO_ID, ARTISTA_ID) VALUES(2, 'Musica 2', 2, 2);
